export const APP_ROLES = {
  PRESIDENT: 'president',
  SECRETARY: 'secretary',
  TREASURER: 'treasurer',
  CULTURAL_HEAD: 'cultural_head',
} as const;

export type AppRole = typeof APP_ROLES[keyof typeof APP_ROLES];

export const PERMISSIONS = {
  // Committee
  CREATE_COMMITTEE: [APP_ROLES.PRESIDENT],
  UPDATE_COMMITTEE: [APP_ROLES.PRESIDENT],
  DELETE_COMMITTEE: [APP_ROLES.PRESIDENT],

  // Resident
  CREATE_RESIDENT: [APP_ROLES.PRESIDENT],
  UPDATE_RESIDENT: [APP_ROLES.PRESIDENT, APP_ROLES.TREASURER],
  DELETE_RESIDENT: [APP_ROLES.PRESIDENT],

  // Gallery
  CREATE_GALLERY: [APP_ROLES.PRESIDENT, APP_ROLES.CULTURAL_HEAD],
  UPDATE_GALLERY: [APP_ROLES.PRESIDENT, APP_ROLES.CULTURAL_HEAD],
  DELETE_GALLERY: [APP_ROLES.PRESIDENT, APP_ROLES.CULTURAL_HEAD],

  // Document
  CREATE_DOCUMENT: [APP_ROLES.PRESIDENT, APP_ROLES.TREASURER],
  UPDATE_DOCUMENT: [APP_ROLES.PRESIDENT, APP_ROLES.TREASURER],
  DELETE_DOCUMENT: [APP_ROLES.PRESIDENT, APP_ROLES.TREASURER],

  // Complaint
  READ_COMPLAINT: [APP_ROLES.PRESIDENT, APP_ROLES.SECRETARY],
  DELETE_COMPLAINT: [APP_ROLES.PRESIDENT, APP_ROLES.SECRETARY],

  // Users
  READ_USERS: [APP_ROLES.PRESIDENT],
  DELETE_USERS: [APP_ROLES.PRESIDENT],

  // Rules
  CREATE_RULE: [APP_ROLES.PRESIDENT],
  UPDATE_RULE: [APP_ROLES.PRESIDENT],
  DELETE_RULE: [APP_ROLES.PRESIDENT],

  // Finance
  UPDATE_FINANCE: [APP_ROLES.PRESIDENT, APP_ROLES.TREASURER],

  // Setting
  UPDATE_SETTING: [APP_ROLES.PRESIDENT],

  // Announcement
  CREATE_ANNOUNCEMENT: [APP_ROLES.PRESIDENT, APP_ROLES.SECRETARY],
  UPDATE_ANNOUNCEMENT: [APP_ROLES.PRESIDENT, APP_ROLES.SECRETARY],
  DELETE_ANNOUNCEMENT: [APP_ROLES.PRESIDENT, APP_ROLES.SECRETARY],
};
